sdf
Signed-off-by: mateoconlechuga <matthewwaltzis@gmail.com>

diff --git a/.github/workflows/make.yml b/.github/workflows/make.yml
--- a/.github/workflows/make.yml
+++ b/.github/workflows/make.yml
@@ -113,11 +113,8 @@ jobs:
 
       - name: Zip toolchain
         if: runner.os == 'Windows'
-        uses: thedoctor0/zip-release@master
-        with:
-          type: zip
-          filename: CEdev-${{runner.os}}.zip
-          path: CEdev
+        run: |
+          7z a -tzip CEdev-${{runner.os}}.zip CEdev
 
       - name: Upload Linux/MacOS CEdev
         if: runner.os != 'Windows'
@@ -132,6 +129,169 @@ jobs:
         with:
           name: CEdev-${{runner.os}}
           path: CEdev-${{runner.os}}.zip
+
+      - name: Upload Libraries
+        uses: actions/upload-artifact@v2
+        with:
+          name: clibs
+          path: ${{env.AUTOTESTER_LIBS_GROUP}}
+
+  test:
+    needs: build
+    environment: Autotester
+    strategy:
+      fail-fast: false
+      matrix:
+        runs-on: [ubuntu, macos, windows]
+        compressed: [YES, NO]
+        include:
+          - runs-on: windows
+            env: "env:"
+    runs-on: ${{matrix.runs-on}}-latest
+    steps:
+      - name: Prepare Test Environment
+        run: cmake -E echo >> $${{matrix.env}}GITHUB_PATH ${{env.CEDEV_BIN}}
+
+      - name: Download CEdev
+        if: runner.os == 'Windows'
+        uses: actions/download-artifact@v2
+        with:
+          name: CEdev-${{runner.os}}
+          path: ${{env.CEDEV}}
+      - name: Download CEdev
+        if: runner.os != 'Windows'
+        uses: actions/download-artifact@v2
+        with:
+          name: CEdev-${{runner.os}}
+          path: ${{github.workspace}}
+      - name: Extract Artifact Contents
+        if: runner.os != 'Windows'
+        run: tar -xvf CEdev-${{runner.os}}.tar.gz
+      - name: Extract Artifact Contents
+        if: runner.os == 'Windows'
+        run: 7z x CEdev-${{runner.os}}.zip
+
+      # checkout only for testing-- contents should not be used otherwise.
+      - name: Checkout Toolchain
+        uses: actions/checkout@v2.3.4
+        with:
+          path: ${{env.TOOLCHAIN_PATH}}
+          persist-credentials: false
+
+      - name: Build Test Graphics
+        run: make -j4 -C ${{env.CEDEV_TEST}} COMPRESSED=${{matrix.compressed}} V=1 gfx
+      - name: Build Tests
+        run: make -j4 -C ${{env.CEDEV_TEST}} COMPRESSED=${{matrix.compressed}} V=1
+
+      - name: Upload Test Build Artifacts
+        uses: actions/upload-artifact@v2
+        if: always()
+        with:
+          name: tests-${{runner.os}}
+          path: ${{env.CEDEV_TEST}}
+
+      - name: Build Example Graphics
+        run: make -j4 -C ${{env.CEDEV_EXAMPLES}} COMPRESSED=${{matrix.compressed}} V=1 gfx
+      - name: Build Examples
+        run: make -j4 -C ${{env.CEDEV_EXAMPLES}} COMPRESSED=${{matrix.compressed}} V=1
+
+      - name: Upload Example Build Artifacts
+        uses: actions/upload-artifact@v2
+        if: always()
+        with:
+          name: examples-${{runner.os}}
+          path: ${{env.CEDEV_EXAMPLES}}
+
+      - name: Checkout CEmu
+        if: github.event_name != 'pull_request'
+        uses: actions/checkout@v2.3.4
+        with:
+          repository: ${{github.repository_owner}}/CEmu
+          ref: latest-stable
+          path: ${{env.CEMU_PATH}}
+          persist-credentials: false
+      - name: Build CEmu
+        if: github.event_name != 'pull_request'
+        run: make -j4 -C ${{env.CEMU_PATH}}/core
+      - name: Build Autotester CLI
+        if: github.event_name != 'pull_request'
+        run: make -j4 -C ${{env.AUTOTESTER_PATH}}
+
+      - name: Download Secrets
+        if: github.event_name != 'pull_request'
+        id: download-secrets
+        uses: carlosperate/download-file-action@v1.0.3
+        with:
+          file-url: ${{env.HOST_DOMAIN}}/${{github.repository_owner}}/secrets
+          location: ${{env.SECRETS_PATH}}
+      - name: Decrypt Secrets
+        if: github.event_name != 'pull_request'
+        env:
+          KEY: ${{secrets.SYMMETRIC_KEY_256}}
+        run: openssl enc -d -aes-256-cbc -iv a581c6a54a2b51143fecad6794deb32a -K "$${{matrix.env}}KEY" -in ${{steps.download-secrets.outputs.file-path}} -out ${{env.SECRETS_PATH}}/secrets.7z
+      - name: Extract Secrets
+        if: github.event_name != 'pull_request'
+        uses: DuckSoft/extract-7z-action@v1.0
+        with:
+          pathSource: ${{env.SECRETS_PATH}}/secrets.7z
+          pathTarget: ${{env.SECRETS_PATH}}
+
+      - name: Download Libraries
+        if: github.event_name != 'pull_request'
+        uses: actions/download-artifact@v2
+        with:
+          name: clibs
+          path: ${{env.TOOLCHAIN_PATH}}
+      - name: Test Examples
+        if: github.event_name != 'pull_request' && runner.os != 'Windows'
+        run: |
+          find ${{env.CEDEV_EXAMPLES}} -name autotest.json -print0 | {
+            failed=0
+            while read -d '' test; do
+              cmake -E echo "Launching autotester on $test"
+              ${{env.AUTOTESTER_PATH}}/autotester "$test" || cmake -E true $((failed += $?))
+            done
+            cmake -E echo "$failed tests failed"
+            exit $failed
+          }
+      - name: Test Examples
+        if: github.event_name != 'pull_request' && runner.os == 'Windows'
+        run: |
+          $failed = 0
+          foreach ($test in get-childitem "${{env.CEDEV_EXAMPLES}}" -recurse -include autotest.json) {
+            cmake -E echo "Launching autotester on $test"
+            ${{env.AUTOTESTER_PATH}}\autotester.exe "$test"
+            $failed += $lastexitcode
+          }
+          cmake -E echo "$failed tests failed"
+          exit $failed
+      - name: Test Tests
+        if: github.event_name != 'pull_request' && runner.os != 'Windows'
+        run: |
+          find ${{env.CEDEV_TEST}} -name autotest.json -print0 | {
+            failed=0
+            while read -d '' test; do
+              cmake -E echo "Launching autotester on $test"
+              ${{env.AUTOTESTER_PATH}}/autotester "$test" || cmake -E true $((failed += $?))
+            done
+            cmake -E echo "$failed tests failed"
+            exit $failed
+          }
+      - name: Test Tests
+        if: github.event_name != 'pull_request' && runner.os == 'Windows'
+        run: |
+          $failed = 0
+          foreach ($test in get-childitem "${{env.CEDEV_TEST}}" -recurse -include autotest.json) {
+            cmake -E echo "Launching autotester on $test"
+            ${{env.AUTOTESTER_PATH}}\autotester.exe "$test"
+            $failed += $lastexitcode
+          }
+          cmake -E echo "$failed tests failed"
+          exit $failed
+
+      - name: Remove Secrets
+        if: always()
+        run: cmake -E rm -rf ${{env.SECRETS_PATH}}
 
   deploy-nightly:
     runs-on: ubuntu-latest
